var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));

// scripts/_ext-v2-cli.mjs
var import_node_fs = require("node:fs");
var import_node_child_process = require("node:child_process");
var import_node_path = require("node:path");
var import_node_url = require("node:url");

// lang/compiler/driver-artifact.mjs
var DRIVER_BYTECODE_B64 = "QKsmYwABMAAAACJBBgABAAAAAGFjAAE5AAAAI0EGAAEAAAAAYQEBAAAAYQEAAAAAYWMAAV8AAAAgQQYAAQEAAABhYwABQQAAACVBEQBjAAFaAAAAJEEGAAEBAAAAYWMAAWEAAAAlQREAYwABegAAACRBBgABAQAAAGEBAAAAAGEBAAAAAGFjAGADAAFBBgABAQAAAGFjAGAxAAFhAQAAAABhYgECAABkA2MBYwIiQRgAYwNjAGMBhIiRZANjAQEBAAAAEGQBQOD/YwNhAQAAAABhYwABAgAAACBBEQBjAQECAAAAIEEGAAEBAAAAYQEAAAAAYQEAAAAAYWICYwCDZAJjAmMBgyFBBgABAAAAAGEBAAAAAGQDYwNjAiJBIQBjAGMDhGMBYwOEIUEGAAEAAAAAYWMDAQEAAAAQZANA1/8BAQAAAGEBAAAAAGEDAAEAAAAAgQEAAAAAIEEGAAEAAAAAYQMBAwEBAAAAAIEBAQAAABBjAIIDAQEAAAAAAwEBAAAAAIEBAQAAABCCAQAAAABhAQAAAABhYgUDAAEAAAAAgQEAAAAAIEEGAAEAAAAAYQMCAQAAAACBZAEBAQAAAGQCYwJjASRBIQADAmMCgWMAYPoAAkEGAAMDYwKBYWMCAQEAAAAQZAJA1/8DBAEAAAAAgWQDYwCDZAQDBGMDAQEAAAAQYwQBAAEAABSCAwRjAwECAAAAEGMEAQABAAATAQABAAAUggMEYwMBAwAAABBjBAEAAAEAEwEAAQAAFIIDBGMDAQQAAAAQYwQBAAAAARMBAAEAABSCAwQBAAAAAGMDAQQAAAAQggEAAAAAZAVjBWMEIkE5AAMEAwQBAAAAAIEBAQAAABBjAGMFhIIDBAEAAAAAAwQBAAAAAIEBAQAAABCCYwUBAQAAABBkBUC//wMCYwEBAQAAABBjAIIDA2MBAQEAAAAQYwOCAwIBAAAAAGMBAQEAAAAQggMDAQAAAABjAQEBAAAAEIJjA2EBAAAAAGFjAAEAAQAAFGBMAQEFYwABAAEAABNkAGMAAQABAAAUYEwBAQVjAAEAAQAAE2QAYwABAAEAABRgTAEBBWMAAQABAAATZABjAAEAAQAAFGBMAQEFAQAAAABhAQAAAABhYgEDAQEAAAAAgWQAAQAAAABgTAEBBQEAAAAAYEwBAQVjAGEBAAAAAGFiAWMBYwABAgAAABARZAJjAgEAAAAAIkEKAGMCAQAAAQAQZAIDAWMAAQEAAAAQYwIBAAEAABSCAwFjAAECAAAAEGMCAQABAAATAQABAAAUggEAAAAAYQEAAAAAYWICAQEAAABkAQMFAQAAAACBAQEAAAAQZAJjAWMCIkEkAAMFYwGBYwBg+gACQQkAYwEBAQAAABFhYwEBAQAAABBkAUDU/wMFAwUBAAAAAIEBAQAAABBjAIIDBQEAAAAAAwUBAAAAAIEBAQAAABCCAwUBAAAAAIEBAQAAABFhAQAAAABhYgIBAQAAAGQBAwYBAAAAAIEBAQAAABBkAmMBYwIiQSQAAwZjAYFjAGD6AAJBCQBjAQEBAAAAEWFjAQEBAAAAEGQBQNT/AQAAAAABAQAAABFhAQAAAABhAwYDBgEAAAAAgQEBAAAAEGMAggMGAQAAAAADBgEAAAAAgQEBAAAAEIIDBgEAAAAAgQEBAAAAEWEBAAAAAGFiAgEBAAAAZAEDBwEAAAAAgQEBAAAAEGQCYwFjAiJBJAADB2MBgWMAYPoAAkEJAGMBAQEAAAARYWMBAQEAAAAQZAFA1P8BAAAAAAEBAAAAEWEBAAAAAGFiAQMIAQAAAACBAQEAAAAgQT0AYwBgWQQBZAFjAQEAAAAAJUEqAAFjAAAAYEwBAQVjAWBMAQEFAwkBAAAAAAMKYwEBAQAAABCBggEAAAAAYWMAYNYDAWQBAQMAAABgTAEBBWMBYEwBAQUDCQEAAAAAAwtjAQEBAAAAEIGCAQAAAABhAQAAAABhYgIDCQEAAAAAgWQBAwgBAAAAAIEBAQAAACBBPwBjAGBZBAFkAmMCAQAAAAAiQQgAYwBgsAQBZAIBZAAAAGBMAQEFYwJgTAEBBQMKYwIBAQAAABBjAYIBAAAAAGFjAGDWAwFkAgEEAAAAYEwBAQVjAmBMAQEFAwtjAgEBAAAAEGMBggEAAAAAYQEAAAAAYWIBAwgBAAAAAIEBAQAAACBBJgBjAGBZBAFkAmMCAQAAAAAlQRMAAwpjAgEBAAAAEGMBggEAAAAAYWMAYNYDAWQCAwtjAgEBAAAAEGMBggEAAAAAYQEAAAAAYWIFAwkBAAAAAIFkAmMAAgQAYPoAAkEdAAGOAAAAYEwBAQUDCQEAAAAAAQUAAACCAQAAAABhYwACDABg+gACQTgAAY8AAABgTAEBBWMCAQQAAAAgQRAAAwkBAAAAAAEFAAAAgkANAAMJAQAAAAABAAAAAIIBAAAAAGFjAAIWAGD6AAJBHQABjQAAAGBMAQEFAwkBAAAAAAEAAAAAggEAAAAAYWMAAh0AYPoAAkEdAAGDAAAAYEwBAQUDCQEAAAAAAQAAAACCAQAAAABhYwACJwBg+gACQR0AAZEAAABgTAEBBQMJAQAAAAABAQAAAIIBAAAAAGFjAAIxAGD6AAJBHQABhAAAAGBMAQEFAwkBAAAAAAEAAAAAggEAAAAAYWMAAjgAYPoAAkEdAAGIAAAAYEwBAQUDCQEAAAAAAQEAAACCAQAAAABhYwACPwBg+gACQR0AAYcAAABgTAEBBQMJAQAAAAABAQAAAIIBAAAAAGFjAAJGAGD6AAJBHQABiQAAAGBMAQEFAwkBAAAAAAEAAAAAggEAAAAAYWMAAlAAYPoAAkEdAAGoAAAAYEwBAQUDCQEAAAAAAQIAAACCAQAAAABhYwACVwBg+gACQR0AAakAAABgTAEBBQMJAQAAAAABAAAAAIIBAAAAAGFjAAJeAGD6AAJBHQABqgAAAGBMAQEFAwkBAAAAAAECAAAAggEAAAAAYWMAAmYAYPoAAkEdAAGrAAAAYEwBAQUDCQEAAAAAAQIAAACCAQAAAABhYwACbgBg+gACQR0AAawAAABgTAEBBQMJAQAAAAABAgAAAIIBAAAAAGFjAAJ3AGD6AAJBJwABrgAAAGBMAQEFAQAAAABgTAEBBQMJAQAAAAABAgAAAIIBAAAAAGFjAAJ/AGD6AAJBJwABrgAAAGBMAQEFAQEAAABgTAEBBQMJAQAAAAABAgAAAIIBAAAAAGFjAAKHAGD6AAJBJwABrgAAAGBMAQEFAQIAAABgTAEBBQMJAQAAAAABAgAAAIIBAAAAAGFjAAKPAGD6AAJBJwABrgAAAGBMAQEFAQMAAABgTAEBBQMJAQAAAAABAgAAAIIBAAAAAGFjAAKXAGD6AAJBJwABrgAAAGBMAQEFAQQAAABgTAEBBQMJAQAAAAABAgAAAIIBAAAAAGFjAAKfAGD6AAJBJwABrgAAAGBMAQEFAQUAAABgTAEBBQMJAQAAAAABAgAAAIIBAAAAAGFjAAKnAGD6AAJBHQABtAAAAGBMAQEFAwkBAAAAAAEAAAAAggEAAAAAYWMAArAAYPoAAkEdAAGwAAAAYEwBAQUDCQEAAAAAAQEAAACCAQAAAABhYwACvQBg+gACQR0AAbEAAABgTAEBBQMJAQAAAAABAAAAAIIBAAAAAGFjAALLAGD6AAJBHQABsgAAAGBMAQEFAwkBAAAAAAEBAAAAggEAAAAAYWMAYO4EAWQDAWAAAABgTAEBBQMBAQAAAACBZAQBAAAAAGQFAQAAAABkBmMDAQAAAAAlQTUAAwxjAwEBAAAAEIFkBWMFAQAAAAAjQQcAAQEAAABkBgMJAQAAAAADDWMDAQEAAAAQgYJADQADCQEAAAAAAQAAAACCYwYBAQAAACBBIwBjBQEAAQAAFGBMAQEFYwUBAAEAABMBAAEAABRgTAEBBUB3AAEAAAAAYEwBAQUBAAAAAGBMAQEFAwABAAAAAIEBAQAAACBBUgADDgMOAQAAAACBAQEAAAAQYwCCAw8DDgEAAAAAgQEBAAAAEGMEggMOAQAAAAADDgEAAAAAgQEBAAAAEIIDDwEAAAAAAw8BAAAAAIEBAQAAABCCYwFgTAEBBQEAAAAAYQEAAAAAYWIFAQEAAABkAAMOAQAAAACBAQEAAAAQZAFjAGMBIkFjAAMOYwCBYO4EAWQCYwIBAAAAACVBQAADDGMCAQEAAAAQgWQDAw9jAIFkBAMBYwQBAQAAABBjAwEAAQAAFIIDAWMEAQIAAAAQYwMBAAEAABMBAAEAABSCYwABAQAAABBkAECV/wEAAAAAYQEAAAAAYWIEAxABAAAAAIFkAQEBAAAAZAIDEQEAAAAAgQEBAAAAEGQDYwJjAyJBNAADEmMCgWMBIEEcAAMRYwKBYwBgegMCBQMSYwIBAAAAAAEBAAAAEYJjAgEBAAAAEGQCQMT/AQEAAABkBGMEQW4AAxEBAAAAAIEBAAAAACNBUwADEgMRAQAAAACBgQEAAAAAAQEAAAARIEEvAAMRAQAAAAADEQEAAAAAgQEBAAAAEYIDEgEAAAAAAxIBAAAAAIEBAQAAABGCQAcAAQAAAABkBEAHAAEAAAAAZARAjf8BAAAAAGEBAAAAAGFiBAMQAQAAAACBZAEBAQAAAGQCAxMBAAAAAIEBAQAAABBkA2MCYwMiQTQAAxRjAoFjASBBHAADE2MCgWMAYHoDAgUDFGMCAQAAAAABAQAAABGCYwIBAQAAABBkAkDE/wEBAAAAZARjBEFuAAMTAQAAAACBAQAAAAAjQVMAAxQDEwEAAAAAgYEBAAAAAAEBAAAAESBBLwADEwEAAAAAAxMBAAAAAIEBAQAAABGCAxQBAAAAAAMUAQAAAACBAQEAAAARgkAHAAEAAAAAZARABwABAAAAAGQEQI3/AQAAAABhAQAAAABhYwADFSVBBgABAAAAAGEDFmMAgQEEAAAAIEERAAMXYwCBYwEgQQYAAQEAAABhAQAAAABhAQAAAABhYwADFSVBBgABAAAAAGEDFmMAgQECAAAAIUEGAAEAAAAAYQMYYwCBYwFg+gACYQEAAAAAYWIOAxZjAIEBAQAAACBBKgABAQAAAGBMAQEFAxdjAIFg8wIBBQMJAQAAAAABAAAAAIJjAAEBAAAAEGEDFmMAgQEGAAAAIEGFAAMZYwCBZAEBAQAAAGQCYwEBAAAAACNBFwBjAgEKAAAAEmQCYwEBAQAAABFkAUDe/wMXYwCBqGMCqKRkAwGgAAAAYEwBAQUBAAAAAGQEYwQBCAAAACJBFwBjA2MEtGBMAQEFYwQBAQAAABBkBEDe/wMJAQAAAAABAgAAAIJjAAEBAAAAEGEDFmMAgQEDAAAAIEFPAAMYYwCBZAVjBWCYAQFkBgECAAAAYEwBAQVjBgEAAQAAFGBMAQEFYwYBAAEAABMBAAEAABRgTAEBBQMJAQAAAAABAQAAAIJjAAEBAAAAEGFjAALXAGCyDgJBKgABAQAAAGBMAQEFAQEAAABg8wIBBQMJAQAAAAABAAAAAIJjAAEBAAAAEGFjAALfAGCyDgJBKgABAQAAAGBMAQEFAQAAAABg8wIBBQMJAQAAAAABAAAAAIJjAAEBAAAAEGFjAALoAGCyDgJBKgABAQAAAGBMAQEFAQAAAABg8wIBBQMJAQAAAAABAAAAAIJjAAEBAAAAEGEDFmMAgQECAAAAIEHBAAMYYwCBZAdjAAEBAAAAEAMVIkGcAGMAAQEAAAAQASgAAABgeQ4CQYgAYwABAgAAABBkAAEAAAAAZAhjAAEpAAAAYHkOAkENAGMAAQEAAAAQZABAUABjAGBuGwFkAAEBAAAAZAhjAAEsAAAAYHkOAkEbAGMAAQEAAAAQYG4bAWQAYwgBAQAAABBkCEDX/2MAASkAAABgeQ4CQQoAYwABAQAAABBkAGMHYwhgtQYCBWMAYWMHYEUFAQVjAAEBAAAAEGFjAAEoAAAAYHkOAkEoAGMAAQEAAAAQYG4bAWQAYwABKQAAAGB5DgJBCQBjAAEBAAAAEGFjAGFjAAFbAAAAYHkOAkG2AGMAAQEAAAAQZAABAAAAAGQJYwABXQAAAGB5DgJBDQBjAAEBAAAAEGQAQFAAYwBgbhsBZAABAQAAAGQJYwABLAAAAGB5DgJBGwBjAAEBAAAAEGBuGwFkAGMJAQEAAAAQZAlA1/9jAAFdAAAAYHkOAkEKAGMAAQEAAAAQZAABgAAAAGBMAQEFYwkBAAEAABRgTAEBBWMJAQABAAATAQABAAAUYEwBAQUDCQEAAAAAAQAAAACCYwBhYwABewAAAGB5DgJB9wFjAAEBAAAAEGQAAYoAAABgTAEBBQMBAQAAAACBZAoBAAAAAGBMAQEFAQAAAABgTAEBBQEAAAAAZAkBAAAAAGQLYwBgexsBZAABAQAAAGQMYwABfQAAAGB5DgJBBwABAAAAAGQMYwxBBgFjAGB7GwFkAAEAAAAAZA0DFmMAgQECAAAAIEEbAGMAAQEAAAAQAToAAABgeQ4CQQcAAQEAAABkDWMNAQEAAAAgQUIAAxhjAIFgmAEBZA4BAgAAAGBMAQEFYw4BAAEAABRgTAEBBWMOAQABAAATAQABAAAUYEwBAQVjAAEBAAAAEGQAQAgAYwBgbhsBZABjAAE6AAAAYHkOAkEKAGMAAQEAAAAQZABjAGBuGwFkAAMJAQAAAACBAQEAAAAgQQcAAQEAAABkCwGLAAAAYEwBAQVjCQEBAAAAEGQJYwBgexsBZABjAAEsAAAAYHkOAkENAGMAAQEAAAAQZABABwABAAAAAGQMQPX+YwBgexsBZABjAAF9AAAAYHkOAkEKAGMAAQEAAAAQZAADAAEAAAAAgQEBAAAAIEEsAAMBYwoBAQAAABBjCQEAAQAAFIIDAWMKAQIAAAAQYwkBAAEAABMBAAEAABSCYwsBAQAAACBBEAADCQEAAAAAAQQAAACCQA0AAwkBAAAAAAEDAAAAgmMAYWMAYQEAAAAAYWICAQEAAABkAWMBQcsAYwABWwAAAGB5DgJBswADCQEAAAAAgWQCYwABAQAAABBkAGMAYG4bAWQAYwABXQAAAGB5DgJBCgBjAAEBAAAAEGQAYwIBAwAAACBBGgABjAAAAGBMAQEFAwkBAAAAAAEAAAAAgkBXAGMCAQQAAAAgQRoAAYwAAABgTAEBBQMJAQAAAAABAQAAAIJAMgABgQAAAGBMAQEFYwIBBQAAACBBEAADCQEAAAAAAQEAAACCQA0AAwkBAAAAAAEAAAAAgkAHAAEAAAAAZAFAMP9jAGEBAAAAAGFjAAEtAAAAYHkOAkE8AAEBAAAAYEwBAQUBAAAAAGDzAgEFYwABAQAAABBgaxUBZAABEQAAAGBMAQEFAwkBAAAAAAEAAAAAgmMAYWMAYOYOAWQAYwBgiRQBZABjAGEBAAAAAGFiA2MAYGsVAWQAAQEAAABkAWMBQR4BYwABKgAAAGB5DgJBYQADCQEAAAAAgWQCYwABAQAAABBgaxUBZAADCQEAAAAAgWQDYwJjA2DSAAJBGgABowAAAGBMAQEFAwkBAAAAAAECAAAAgkAXAAESAAAAYEwBAQUDCQEAAAAAAQAAAACCQKwAYwABLwAAAGB5DgJBYQADCQEAAAAAgWQCYwABAQAAABBgaxUBZAADCQEAAAAAgWQDYwJjA2DSAAJBGgABpAAAAGBMAQEFAwkBAAAAAAECAAAAgkAXAAETAAAAYEwBAQUDCQEAAAAAAQAAAACCQD0AYwABJQAAAGB5DgJBKABjAAEBAAAAEGBrFQFkAAEUAAAAYEwBAQUDCQEAAAAAAQAAAACCQAcAAQAAAABkAUDd/mMAYQEAAAAAYWIEYwBgzhUBZAABAQAAAGQBYwFBOAFjAAErAAAAYHkOAkGxAAMJAQAAAACBZAJjAAEBAAAAEGDOFQFkAAMJAQAAAACBZAMBAAAAAGQEYwIBAQAAACBBBwABAQAAAGQEYwMBAQAAACBBBwABAQAAAGQEYwQBAQAAACBBGgABkQAAAGBMAQEFAwkBAAAAAAEBAAAAgkA8AGMCYwNg0gACQRoAAaEAAABgTAEBBQMJAQAAAAABAgAAAIJAFwABEAAAAGBMAQEFAwkBAAAAAAEAAAAAgkB2AGMAAS0AAABgeQ4CQWEAAwkBAAAAAIFkAmMAAQEAAAAQYM4VAWQAAwkBAAAAAIFkA2MCYwNg0gACQRoAAaIAAABgTAEBBQMJAQAAAAABAgAAAIJAFwABEQAAAGBMAQEFAwkBAAAAAAEAAAAAgkAHAAEAAAAAZAFAw/5jAGEBAAAAAGFiA2MAYAsXAWQAYwAC8wBgsg4CQY4AAwkBAAAAAIFkAWMAAQEAAAAQZAABAAAAAGQCYwAC+QBgsg4CQREAAQEAAABkAmMAAQEAAAAQZABjAGALFwFkAAMJAQAAAACBZANjAkENAAEhAAAAYEwBAQVAIgBjAWMDYNIAAkENAAGnAAAAYEwBAQVACgABIAAAAGBMAQEFAwkBAAAAAAEAAAAAgmMAYWMAATwAAABgeQ4CQVQAAwkBAAAAAIFkAWMAAQEAAAAQYAsXAWQAAwkBAAAAAIFkA2MBYwNg0gACQQ0AAaUAAABgTAEBBUAKAAEiAAAAYEwBAQUDCQEAAAAAAQAAAACCYwBhYwABPgAAAGB5DgJBVAADCQEAAAAAgWQBYwABAQAAABBgCxcBZAADCQEAAAAAgWQDYwFjA2DSAAJBDQABpgAAAGBMAQEFQAoAASMAAABgTAEBBQMJAQAAAAABAAAAAIJjAGFjAAEsAQAAYHkOAkEoAGMAAQEAAAAQYAsXAWQAASQAAABgTAEBBQMJAQAAAAABAAAAAIJjAGFjAAEtAQAAYHkOAkEoAGMAAQEAAAAQYAsXAWQAASUAAABgTAEBBQMJAQAAAAABAAAAAIJjAGFjAGEBAAAAAGFjAAL5AGCyDgJBKABjAAEBAAAAEGA/GgFkAAEwAAAAYEwBAQUDCQEAAAAAAQAAAACCYwBhYwBgYhgBYQEAAAAAYWICYwBgPxoBZAABAQAAAGQBYwFBUwBjAAIAAWCyDgJBPQABQQAAAGBMAQEFYFEDAGQCYwABAQAAABBgPxoBZABjAgMBAQAAAACBYHoDAgUDCQEAAAAAAQAAAACCQAcAAQAAAABkAUCo/2MAYQEAAAAAYWICYwBggBoBZAABAQAAAGQBYwFBXQBjAAIHAWCyDgJBRwABMAAAAGBMAQEFAUEAAABgTAEBBWBRAwBkAmMAAQEAAAAQYIAaAWQAYwIDAQEAAAAAgWB6AwIFAwkBAAAAAAEAAAAAgkAHAAEAAAAAZAFAnv9jAGEBAAAAAGFjAGDyGgFhAQAAAABhYgEBAQAAAGQBYwFBNwBjAAMVJUEKAAEAAAAAZAFAIgADFmMAgQEFAAAAIEENAGMAAQEAAAAQZABABwABAAAAAGQBQMT/YwBhAQAAAABhYgIBAQAAAGQBYwFBZwBjAGB7GwFkAGMAAxUlQQoAAQAAAABkAUBKAGMAAg0BYLIOAkEKAAEAAAAAZAFANABjAAIVAWCyDgJBCgABAAAAAGQBQB4AYwBg2BwBZAJjAmMAIEEKAAEAAAAAZAFABABjAmQAQJT/YwBhAQAAAABhYgEDGgEAAAAAAQAAAACCYwACHAFgsg4CQW0AYwABAQAAABBkAAEBAAAAZAFjAUFXAGMAAxUlQQoAAQAAAABkAUBCAAMWYwCBAQIAAAAgQS0AAxhjAIFgsAQBBQMaAQAAAAADGgEAAAAAgQEBAAAAEIJjAAEBAAAAEGQAQAcAAQAAAABkAUCk/2MAYQEAAAAAYWIVYwBgexsBZABjAAMVJUEDAGMAYWMAAiQBYLIOAkFXAGMAAQEAAAAQYG4bAWQAAwkBAAAAAIEBAQAAACBBDQABUQAAAGBMAQEFQCgAAwkBAAAAAIEBAgAAACBBDQABrQAAAGBMAQEFQAoAAVAAAABgTAEBBWMAYWMAAisBYLIOAkE9AWMAAQEAAAAQZAADGGMAgWQBYwABAQAAABBkAGMAAVsAAABgeQ4CQewAYwFgRQUBBQMJAQAAAACBZAJjAAEBAAAAEGQAYwBgbhsBZABjAAFdAAAAYHkOAkEKAGMAAQEAAAAQZABjAAIyAWCyDgJBCgBjAAEBAAAAEGQAYwBgbhsBZAADCQEAAAAAgWQDAQAAAABkBGMCAQMAAAAgQQcAAQEAAABkBGMCAQQAAAAgQQcAAQEAAABkBGMEAQEAAAAgQTkAAYsAAABgTAEBBQEFAAAAYEwBAQVjAwEBAAAAIEEXAGMCAQMAAAAgQQwAYwEBBAAAAGBbBgIFQAoAAYIAAABgTAEBBQMJAQAAAAABAAAAAIJjAGFjAAIyAWCyDgJBCgBjAAEBAAAAEGQAYwBgbhsBZABjAWDNBQEFYwBhYwACOAFgsg4CQbUAYwABAQAAABBkAAEAAAAAZAVjAAMVIkEVAAMWYwCBAQUAAAAhQQcAAQEAAABkBWMFAQEAAAAgQQsAYwBgbhsBZABAIQABAQAAAGBMAQEFAQAAAABg8wIBBQMJAQAAAAABAAAAAIIDCAEAAAAAgQEBAAAAIEEyAAMJAQAAAACBAQEAAAAgQSEAAxsBAAAAAIEBAAAAACNBEAADDQMbAQAAAACBAQEAAACCAWEAAABgTAEBBWMAYWMAAkIBYLIOAkFxAAFAAAAAYEwBAQVgUQMAZAYDEQMRAQAAAACBAQEAAAAQYwaCAxIDEQEAAAAAgQEBAAAAEAMQAQAAAACBggMRAQAAAAADEQEAAAAAgQEBAAAAEIIDEgEAAAAAAxIBAAAAAIEBAQAAABCCYwABAQAAABBhYwACSwFgsg4CQXEAAUAAAABgTAEBBWBRAwBkBwMTAxMBAAAAAIEBAQAAABBjB4IDFAMTAQAAAACBAQEAAAAQAxABAAAAAIGCAxMBAAAAAAMTAQAAAACBAQEAAAAQggMUAQAAAAADFAEAAAAAgQEBAAAAEIJjAAEBAAAAEGFjAAJXAWCyDgJB2wBjAAEBAAAAEGBuGwFkAAFBAAAAYEwBAQVgUQMAZAhjAGDJGwFkAGMAAg0BYLIOAkGBAGMAAQEAAAAQZAABAAAAAGQJYwACVwFgsg4CQQcAAQEAAABkCQFAAAAAYEwBAQVgUQMAZApjCAMBAQAAAACBYHoDAgVjCQEBAAAAIEELAGMAYNgcAWQAQAgAYwBgyRsBZABjCgMBAQAAAACBYHoDAgVjCQEBAAAAIEEDAGMAYUAPAGMIAwEBAAAAAIFgegMCBWMAAhUBYLIOAkEKAGMAAQEAAAAQZABjAGFjAAJdAWCyDgJBsQADAQEAAAAAgWQLYwABAQAAABBgbhsBZAABQQAAAGBMAQEFYFEDAGQIAxABAAAAAAMQAQAAAACBAQEAAAAQgmMAYMkbAWQAYwtglA0BBQFAAAAAYEwBAQVgUQMAZAxjDGMLYHoDAgVjCAMBAQAAAACBYHoDAgUDAQEAAAAAgWCvDAEFAxABAAAAAAMQAQAAAACBAQEAAAARgmMAAhUBYLIOAkEKAGMAAQEAAAAQZABjAGFjAAJmAWCyDgJBHQJjAAEBAAAAEGQAYwACbQFgsg4CQQoAYwABAQAAABBkAAMYYwCBZA1jAAEBAAAAEGQAYwACdQFgsg4CQQoAYwABAQAAABBkAAMcAQAAAAADHAEAAAAAgQEBAAAAEIICewEDHAEAAAAAgYeRZA4ChAEDHAEAAAAAgYeRZA9jAGBuGwFkAAMJAQAAAACBZBBjDmDNBQEFAQEAAABgTAEBBQEAAAAAYPMCAQUDCQEAAAAAAQAAAACCYw9gzQUBBQMBAQAAAACBZAtjD2BFBQEFYw5gRQUBBQGDAAAAYEwBAQUBIgAAAGBMAQEFAUEAAABgTAEBBWBRAwBkCGMOYEUFAQVjD2BFBQEFAYEAAABgTAEBBWMQAQUAAAAgQRAAAwkBAAAAAAEBAAAAgkANAAMJAQAAAAABAAAAAIJjDWDNBQEFAxABAAAAAAMQAQAAAACBAQEAAAAQgmMAYMkbAWQAAwEBAAAAAIFglA0BBWMPYEUFAQUBAQAAAGBMAQEFAQEAAABg8wIBBQEQAAAAYEwBAQUDCQEAAAAAAQAAAACCYw9gzQUBBQFAAAAAYEwBAQVgUQMAZAxjDGMLYHoDAgVjCAMBAQAAAACBYHoDAgUDAQEAAAAAgWCvDAEFAxABAAAAAAMQAQAAAACBAQEAAAARggMcAQAAAAADHAEAAAAAgQEBAAAAEYJjAAIVAWCyDgJBCgBjAAEBAAAAEGQAYwBhYwACMgFgsg4CQUgCYwABAQAAABBkAAMYYwCBZBFjAAEBAAAAEGQAYwBkEgMGAQAAAAABAAAAAIIDCgEAAAAAAQAAAACCYwBgRxwBZAADGgEAAAAAgWQTAx0BAAAAAIEBAQAAACBBXAADAAEAAAAAgWQUAwABAAAAAAEAAAAAggMIAQAAAAABAQAAAIJjAGDJGwFkAAMIAQAAAAABAAAAAIIDAAEAAAAAYxSCYwACFQFgsg4CQQoAYwABAQAAABBkAGMAYWMRYO4EAWQVYxUBAAAAACJBDwEDBwMHAQAAAACBAQEAAAAQYxGCAwwDBwEAAAAAgQEBAAAAEAEAAAAAggMeAwcBAAAAAIEBAQAAABBjE4IDDQMHAQAAAACBAQEAAAAQAQAAAACCAx8DBwEAAAAAgQEBAAAAEAEAAAAAggMgAwcBAAAAAIEBAQAAABBjEoIDBwEAAAAAAwcBAAAAAIEBAQAAABCCAwwBAAAAAAMMAQAAAACBAQEAAAAQggMeAQAAAAADHgEAAAAAgQEBAAAAEIIDDQEAAAAAAw0BAAAAAIEBAQAAABCCAx8BAAAAAAMfAQAAAACBAQEAAAAQggMgAQAAAAADIAEAAAAAgQEBAAAAEIIDBwEAAAAAgQEBAAAAEWQVAxsBAAAAAGMVAQEAAAAQggMIAQAAAAABAQAAAIJjAGDJGwFkAAMfYxUBAQAAABADBgEAAAAAgWMTEYIDCAEAAAAAAQAAAACCAxsBAAAAAAEAAAAAgmMAAhUBYLIOAkEKAGMAAQEAAAAQZABjAGEDFmMAgQECAAAAIEEiAGMAYG4bAWQAAQUAAABgTAEBBQMJAQAAAAABAAAAAIJjAGFjAGEBAAAAAGECjQGwBCEBIE4AAIkEFgEgTgAAiQQXASBOAACJBBkBIE4AAIkEGAEAAAAABBUDIYMEIgEAAAAABCMDIwMiIkH1AwMhAyOEBCQDJAEgAAAAIEENAAMjAQEAAAAQBCNA0wMDJAEJAAAAIEENAAMjAQEAAAAQBCNAuwMDJAENAAAAIEENAAMjAQEAAAAQBCNAowMDJAEKAAAAIEEhAAMWAxUBBQAAAIIDFQEBAAAAEAQVAyMBAQAAABAEI0B3AwMkASMAAAAgQUYAAQEAAAAEJQMlQTcAAyMDIiVBCgABAAAAAAQlQCIAAyEDI4QBCgAAACBBCgABAAAAAAQlQAoAAyMBAQAAABAEI0DE/0AmAwMkYAMAAUFyAQMjBCYBAQAAAAQlAyVBNQADJgMiJUEKAAEAAAAABCVAIAADIQMmhGADAAFBDQADJgEBAAAAEAQmQAcAAQAAAAAEJUDG/wEAAAAABCcDIwQoAygDJiJBIwADJwEKAAAAEgMhAyiEEAEwAAAAEQQnAygBAQAAABAEKEDV/wEAAAAABCkBAAAAAAQqAyYDIiJBoAADIQMmhAEuAAAAIEGSAAMmAQEAAAAQAyIiQYQAAyEDJgEBAAAAEIRgAwABQXIAAQEAAAAEKgMmAQEAAAAQBCYBAQAAAAQlAyVBVQADJgMiJUEKAAEAAAAABCVAQAADIQMmhGADAAFBLQADJwEKAAAAEgMhAyaEEAEwAAAAEQQnAykBAQAAABAEKQMmAQEAAAAQBCZABwABAAAAAAQlQKb/AyoBAQAAACBBDQADFgMVAQYAAACCQAoAAxYDFQEBAAAAggMXAxUDJ4IDGQMVAymCAxUBAQAAABAEFQMmBCNAqwEDJAEiAAAAIEGDAAMjAQEAAAAQBCYBAQAAAAQrAytBNwADJgMiJUEKAAEAAAAABCtAIgADIQMmhAEiAAAAIEEKAAEAAAAABCtACgADJgEBAAAAEAQmQMT/AxYDFQEDAAAAggMYAxUDIQMjAQEAAAAQAyZgogADggMVAQEAAAAQBBUDJgEBAAAAEAQjQB0BAyRgMQABQW8AAyMEJgEBAAAABCUDJUE1AAMmAyIlQQoAAQAAAAAEJUAgAAMhAyaEYIYAAUENAAMmAQEAAAAQBCZABwABAAAAAAQlQMb/AxYDFQECAAAAggMYAxUDIQMjAyZgogADggMVAQEAAAAQBBUDJgQjQKUAAyQELAMkATwAAAAgQTMAAyMBAQAAABADIiJBJQADIQMjAQEAAAAQhAE9AAAAIEERAAEsAQAABCwDIwEBAAAAEAQjAyQBPgAAACBBMwADIwEBAAAAEAMiIkElAAMhAyMBAQAAABCEAT0AAAAgQREAAS0BAAAELAMjAQEAAAAQBCMDFgMVAQQAAACCAxcDFQMsggMVAQEAAAAQBBUDIwEBAAAAEAQjQAP8AQAAAQCJBAEDAQEAAAAAAQAAAACCAQABAACJBAUDBQEAAAAAAQAAAACCAQABAACJBAsDCwEAAAAAAQAAAACCAQABAACJBAYDBgEAAAAAAQAAAACCAQABAACJBAoDCgEAAAAAAQAAAACCAQABAACJBAcDBwEAAAAAAQAAAACCAQABAACJBAwDDAEAAAAAAQAAAACCAQABAACJBB4DHgEAAAAAAQAAAACCAQABAACJBA0DDQEAAAAAAQAAAACCAQABAACJBB8DHwEAAAAAAQAAAACCAQABAACJBCADIAEAAAAAAQAAAACCAQIAAACJBBsDGwEAAAAAAQAAAACCAQACAACJBA4DDgEAAAAAAQAAAACCAQACAACJBA8DDwEAAAAAAQAAAACCAQIAAACJBAgDCAEAAAAAAQAAAACCAQIAAACJBAkDCQEAAAAAAQAAAACCAQQAAACJBBoDGgEAAAAAAQAAAACCAQIAAACJBAADAAEAAAAAAQAAAACCAQIAAACJBB0DHQEAAAAAAQAAAACCAQCAAACJBAQDBAEAAAAAAQAAAACCAQABAACJBAIDAgEAAAAAAQAAAACCAQABAACJBAMDAwEAAAAAAQAAAACCAQABAACJBBEDEQEAAAAAAQAAAACCAQABAACJBBIDEgEAAAAAAQAAAACCAQABAACJBBMDEwEAAAAAAQAAAACCAQABAACJBBQDFAEAAAAAAQAAAACCAQIAAACJBBADEAEAAAAAAQAAAACCAQIAAACJBBwDHAEAAAAAAQAAAACCAwABAAAAAAEAAAAAggMdAQAAAAABAAAAAIIBAAAAAAQtAy0BAgAAACJBagABAAAAAAQuAwUBAAAAAAEAAAAAggMLAQAAAAABAAAAAIIBAQAAAAQvAy9BMAADLmDYHAEEMAMwAy4gQQoAAQAAAAAEL0AEAAMwBC4DLgMVJUEHAAEAAAAABC9Ay/8DLQEBAAAAEAQtQIv/AwUBAAAAAAEAAAAAggMLAQAAAAABAAAAAIIDDgEAAAAAAQAAAACCAw8BAAAAAAEAAAAAggMBAQAAAAABAAAAAIIDAAEAAAAAAQEAAACCAUAAAABgTAEBBWBRAwAEMQEBAAAABCMDBwEAAAAAgQEBAAAAEAQyAyMDMiJBvQADDAMjAwEBAAAAAIGCAwYBAAAAAAEAAAAAggMKAQAAAAABAAAAAIIDIAMjgQQuAy5gRxwBBC4DHwMjgQQzAzMBAAAAACNBEQABYgAAAGBMAQEFAzNgTAEBBQMIAQAAAAABAQAAAIIDGwEAAAAAAyOCAy5gyRsBBC4BAQAAAGBMAQEFAQAAAABg8wIBBQFhAAAAYEwBAQUDCAEAAAAAAQAAAACCAxsBAAAAAAEAAAAAggMjAQEAAAAQBCNAO/8DMQMBAQAAAACBYHoDAgUDHQEAAAAAAQEAAACCAQAAAAAELgEBAAAABC8DL0EwAAMuYNgcAQQwAzADLiBBCgABAAAAAAQvQAQAAzAELgMuAxUlQQcAAQAAAAAEL0DL/wH/AAAAYEwBAQVgHwwABQMBAQAAAACBUAEBAAAABDQDAQEAAAAAgQEBAAAAEAQ1AzQDNSJBEwADAQM0gVADNAEBAAAAEAQ0QOX/AwQBAAAAAIFQAQEAAAAENAMEAQAAAACBAQEAAAAQBDUDNAM1IkETAAMEAzSBUAM0AQEAAAAQBDRA5f//";
var DRIVER_POOL_B64 = "AAAAAAQAAABrZXlzBgAAAHZhbHVlcwMAAABoYXMGAAAAbGVuZ3RoBgAAAGNvbmNhdAMAAABvcmQDAAAAY2hyAwAAAHN0cgYAAABta2xpc3QDAAAAaTJmAwAAAGYyaQQAAABmbmVnBAAAAGZhYnMFAAAAZnNxcnQEAAAAZnNpbgQAAABmY29zBAAAAGZ0YW4EAAAAZmV4cAQAAABmbG9nBAAAAGZwb3cFAAAAZmJ5dGUJAAAAcmVhZF9maWxlCgAAAHdyaXRlX2ZpbGUIAAAAaHR0cF9nZXQEAAAAdHJ1ZQUAAABmYWxzZQcAAABub3RoaW5nAgAAAGlzAwAAAG5vdAMAAABhbmQCAAAAb3IEAAAAZWxzZQMAAABlbmQEAAAAd2l0aAMAAABzYXkDAAAAc2V0AgAAAHRvBgAAAHJldHVybgUAAABicmVhawgAAABjb250aW51ZQIAAABpZgUAAAB3aGlsZQMAAABmb3IEAAAAZWFjaAIAAABpbgUAAABfZmVfbAUAAABfZmVfaQcAAAA8c3RkaW4+";

// lang/compiler/compile-self.mjs
var import_meta = {};
var decoder = new TextDecoder();
var encoder = new TextEncoder();
function b64ToBytes(b64) {
  if (typeof atob === "function") {
    const bin = atob(b64);
    const out = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
    return out;
  }
  return new Uint8Array(Buffer.from(b64, "base64"));
}
var cached = null;
var seedLoader = null;
function setSeedLoader(fn) {
  seedLoader = fn;
  cached = null;
}
var SEED_ASSET_PATH = "/wasm/sdev-seed.wasm";
async function defaultSeedBytes() {
  if (typeof process !== "undefined" && process.versions?.node) {
    const { readFile } = await import("node:fs/promises");
    const base = new URL("../../public", import_meta.url).href.replace(/\/$/, "");
    return readFile(new URL(base + SEED_ASSET_PATH));
  }
  const res = await fetch(SEED_ASSET_PATH);
  if (!res.ok) throw new Error(`fetch seed VM: ${res.status}`);
  return new Uint8Array(await res.arrayBuffer());
}
async function init() {
  if (cached) return cached;
  const wasmBytes = await (seedLoader ? seedLoader() : defaultSeedBytes());
  cached = {
    wasmModule: await WebAssembly.compile(wasmBytes),
    driverBc: b64ToBytes(DRIVER_BYTECODE_B64),
    driverPool: b64ToBytes(DRIVER_POOL_B64)
  };
  return cached;
}
async function compile(userSrc) {
  const { wasmModule, driverBc, driverPool } = await init();
  const srcBytes = encoder.encode(userSrc);
  const dumped = [];
  let mem;
  let allocStr;
  const inst = await WebAssembly.instantiate(wasmModule, {
    env: {
      host_say_i32: (n) => dumped.push(String(n)),
      host_say_str: (ptr, len) => dumped.push(decoder.decode(new Uint8Array(mem.buffer, ptr, len))),
      host_say_f64: (x) => {
      },
      host_fmath: (op, a, b) => [Math.sin, Math.cos, Math.tan, Math.exp, Math.log, (x, y) => Math.pow(x, y)][op](a, b),
      // Any read serves the program under compilation — the driver only
      // ever asks for "<stdin>".
      host_read_file: () => {
        const dst = allocStr(srcBytes.length);
        new Uint8Array(mem.buffer, dst + 4, srcBytes.length).set(srcBytes);
        return dst;
      },
      host_write_file: () => -1,
      host_http_get: () => 0
    }
  });
  mem = inst.exports.memory;
  allocStr = inst.exports.alloc_str;
  new Uint8Array(mem.buffer).set(driverPool, 0);
  const codeBase = inst.exports.code_base();
  new Uint8Array(mem.buffer).set(driverBc, codeBase);
  inst.exports.set_prog_len(driverBc.length);
  inst.exports.run();
  let cursor = 0;
  const bcCount = parseInt(dumped[cursor++], 10);
  const bytecode = new Uint8Array(bcCount);
  for (let i = 0; i < bcCount; i++) bytecode[i] = parseInt(dumped[cursor++], 10) & 255;
  const poolCount = parseInt(dumped[cursor++], 10);
  const stringPool = new Uint8Array(poolCount);
  for (let i = 0; i < poolCount; i++) stringPool[i] = parseInt(dumped[cursor++], 10) & 255;
  return { bytecode, stringPool };
}

// scripts/_ext-v2-cli.mjs
var import_meta2 = {};
var decoder2 = new TextDecoder();
function here() {
  try {
    return (0, import_node_path.dirname)((0, import_node_url.fileURLToPath)(import_meta2.url));
  } catch {
    return __dirname;
  }
}
setSeedLoader(async () => (0, import_node_fs.readFileSync)((0, import_node_path.join)(here(), "sdev-seed.wasm")));
async function main() {
  const file = process.argv[2];
  if (!file) {
    console.error("usage: sdev-v2 <file.sdev>");
    process.exit(2);
  }
  const src = (0, import_node_fs.readFileSync)(file, "utf8");
  const { bytecode, stringPool } = await compile(src);
  const wasmBytes = (0, import_node_fs.readFileSync)((0, import_node_path.join)(here(), "sdev-seed.wasm"));
  const module2 = await WebAssembly.compile(wasmBytes);
  let mem, allocStr;
  const write = (s) => process.stdout.write(s + "\n");
  const inst = await WebAssembly.instantiate(module2, {
    env: {
      host_say_i32: (n) => write(String(n)),
      host_say_str: (ptr, len) => write(decoder2.decode(new Uint8Array(mem.buffer, ptr, len))),
      host_say_f64: (x) => write(String(x)),
      host_fmath: (op, a, b) => [Math.sin, Math.cos, Math.tan, Math.exp, Math.log, (x, y) => Math.pow(x, y)][op](a, b),
      host_read_file: (ptr, len) => {
        try {
          const path = decoder2.decode(new Uint8Array(mem.buffer, ptr, len));
          const buf = (0, import_node_fs.readFileSync)(path);
          const dst = allocStr(buf.length);
          new Uint8Array(mem.buffer, dst + 4, buf.length).set(buf);
          return dst;
        } catch {
          return allocStr(0);
        }
      },
      host_write_file: (pPtr, pLen, dPtr, dLen) => {
        try {
          const path = decoder2.decode(new Uint8Array(mem.buffer, pPtr, pLen));
          (0, import_node_fs.writeFileSync)(path, new Uint8Array(mem.buffer, dPtr, dLen).slice());
          return 0;
        } catch {
          return -1;
        }
      },
      host_http_get: (ptr, len) => {
        try {
          const url = decoder2.decode(new Uint8Array(mem.buffer, ptr, len));
          const out = (0, import_node_child_process.execFileSync)("curl", ["-sSL", "--max-time", "15", url], { maxBuffer: 8 * 1024 * 1024 });
          const dst = allocStr(out.length);
          new Uint8Array(mem.buffer, dst + 4, out.length).set(out);
          return dst;
        } catch {
          return 0;
        }
      }
    }
  });
  mem = inst.exports.memory;
  allocStr = inst.exports.alloc_str;
  const memU8 = new Uint8Array(mem.buffer);
  memU8.set(stringPool, 0);
  const codeBase = inst.exports.code_base();
  memU8.set(bytecode, codeBase);
  inst.exports.set_prog_len(bytecode.length);
  inst.exports.run();
}
main().catch((e) => {
  console.error(String(e && e.message ? e.message : e));
  process.exit(1);
});
