// Milestone 5p — bake the self-hosted driver bytecode.
//
// The driver program (codegen.sdev + inline lexer + drive block) is
// source-independent, so it only has to be compiled once. This script uses
// the JS bootstrap as a *build-time* tool and writes the result to
// `lang/compiler/driver-artifact.mjs`. Nothing at runtime imports the
// bootstrap any more.
//
//   node scripts/build-driver.mjs
//
// `scripts/test-driver-artifact.mjs` verifies the checked-in bytes still
// match what the bootstrap produces.

import { readFile, writeFile } from 'node:fs/promises';
import { compile as bootstrapCompile } from '../lang/bootstrap/compile.mjs';
import { driverProgram } from '../lang/compiler/compile-self.mjs';

export async function buildDriver() {
  const codegenSrc = await readFile(new URL('../lang/compiler/codegen.sdev', import.meta.url), 'utf8');
  const { bytecode, stringPool } = bootstrapCompile(driverProgram(codegenSrc));
  return { bytecode, stringPool };
}

const b64 = (u8) => Buffer.from(u8).toString('base64');

function wrap(s, width = 100) {
  const lines = [];
  for (let i = 0; i < s.length; i += width) lines.push("  '" + s.slice(i, i + width) + "'");
  return lines.join(' +\n');
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const { bytecode, stringPool } = await buildDriver();
  const out = `// GENERATED by scripts/build-driver.mjs — do not edit by hand.
// Bytecode for the self-hosted SDEV driver (codegen.sdev + inline lexer).
// bytecode: ${bytecode.length} bytes, string pool: ${stringPool.length} bytes.

export const DRIVER_BYTECODE_B64 =
${wrap(b64(bytecode))};

export const DRIVER_POOL_B64 =
${wrap(b64(stringPool))};
`;
  await writeFile(new URL('../lang/compiler/driver-artifact.mjs', import.meta.url), out);
  console.log(`driver-artifact.mjs written — bc=${bytecode.length}, pool=${stringPool.length}`);
}
