// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@3.0.4";

// src/lib/mcp/tools/files.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/files.ts
var notAuthed = () => ({ content: [{ type: "text", text: "Not authenticated" }], isError: true });
var listFiles = defineTool({
  name: "list_files",
  title: "List my SDEV files",
  description: "List the signed-in user's saved SDEV files (name, id, runtime, last update).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_args, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const { data, error } = await supabaseForUser(ctx).from("code_files").select("id,name,runtime,dialect_slug,updated_at").order("updated_at", { ascending: false }).limit(200);
    if (error) throw new ToolError(error.message);
    const files = (data ?? []).map((f) => ({
      id: f.id,
      name: f.name,
      runtime: f.runtime ?? null,
      dialect: f.dialect_slug ?? null,
      updated_at: f.updated_at
    }));
    return { content: [{ type: "text", text: JSON.stringify(files) }], structuredContent: { files } };
  }
});
var readFile = defineTool({
  name: "read_file",
  title: "Read an SDEV file",
  description: "Read the full source of one of the signed-in user's SDEV files by id.",
  inputSchema: { id: z.string().uuid().describe("File id from list_files.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const { data, error } = await supabaseForUser(ctx).from("code_files").select("id,name,content").eq("id", id).maybeSingle();
    if (error) throw new ToolError(error.message);
    if (!data) throw new ToolError("File not found");
    return { content: [{ type: "text", text: `// ${data.name}
${data.content}` }] };
  }
});
var saveFile = defineTool({
  name: "save_file",
  title: "Save an SDEV file",
  description: "Create a new SDEV file, or overwrite an existing one when an id is given.",
  inputSchema: {
    name: z.string().trim().min(1).max(200).describe("File name, e.g. quiz.sdev."),
    content: z.string().max(5e5).describe("SDEV source code."),
    id: z.string().uuid().optional().describe("Existing file id to overwrite.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ name, content, id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthed();
    const db = supabaseForUser(ctx);
    const q = id ? db.from("code_files").update({ name, content }).eq("id", id).select("id,name").maybeSingle() : db.from("code_files").insert({ name, content, user_id: ctx.getUserId(), language: "sdev" }).select("id,name").maybeSingle();
    const { data, error } = await q;
    if (error) throw new ToolError(error.message);
    if (!data) throw new ToolError("File not found");
    return { content: [{ type: "text", text: `Saved ${data.name} (${data.id})` }] };
  }
});

// src/lib/mcp/tools/community.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@3.0.4";
import { z as z2 } from "npm:zod@^3.25.76";
var listDialects = defineTool2({
  name: "list_dialects",
  title: "List dialects",
  description: "List the signed-in user's own SDEV dialects plus publicly shared ones, optionally filtered by text.",
  inputSchema: { search: z2.string().trim().max(100).optional().describe("Filter by name.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supabaseForUser(ctx).from("dialects").select("id,name,slug,description,languages,visibility,latest_version,user_id").order("install_count", { ascending: false }).limit(100);
    if (search) q = q.ilike("name", `%${search}%`);
    const { data, error } = await q;
    if (error) throw new ToolError2(error.message);
    const me = ctx.getUserId();
    const dialects = (data ?? []).map((d) => ({
      name: d.name,
      slug: d.slug,
      description: d.description ?? null,
      languages: d.languages ?? [],
      visibility: d.visibility,
      version: d.latest_version,
      mine: d.user_id === me
    }));
    return { content: [{ type: "text", text: JSON.stringify(dialects) }], structuredContent: { dialects } };
  }
});
var listGists = defineTool2({
  name: "list_shared_programs",
  title: "List shared programs",
  description: "List publicly shared SDEV programs, optionally filtered by title.",
  inputSchema: { search: z2.string().trim().max(100).optional().describe("Filter by title.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = supabaseForUser(ctx).from("gists").select("slug,title,description,created_at").order("created_at", { ascending: false }).limit(50);
    if (search) q = q.ilike("title", `%${search}%`);
    const { data, error } = await q;
    if (error) throw new ToolError2(error.message);
    const programs = (data ?? []).map((g) => ({
      slug: g.slug,
      title: g.title,
      description: g.description ?? null,
      url: `https://web.sdev.codes/g/${g.slug}`
    }));
    return { content: [{ type: "text", text: JSON.stringify(programs) }], structuredContent: { programs } };
  }
});
var readGist = defineTool2({
  name: "read_shared_program",
  title: "Read a shared program",
  description: "Read the source of a publicly shared SDEV program by its slug.",
  inputSchema: { slug: z2.string().trim().min(1).max(100).describe("Program slug.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await supabaseForUser(ctx).from("gists").select("title,content").eq("slug", slug).maybeSingle();
    if (error) throw new ToolError2(error.message);
    if (!data) throw new ToolError2("Program not found");
    return { content: [{ type: "text", text: `// ${data.title}
${data.content}` }] };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ygzqjekxzvsrkhuqhqbp";
var mcp_default = defineMcp({
  name: "sdev-simple-developer-language",
  title: "Sdev: Simple Developer Language",
  version: "0.1.0",
  instructions: "Tools for SDEV, a beginner-friendly programming language. Read and save the user's SDEV files, browse dialects, and read publicly shared programs.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [listFiles, readFile, saveFile, listDialects, listGists, readGist]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@3.0.4/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
